### ISSUE TITLE
Add Environmental Ed pag

### ISSUE THREAD

**Issue by jupago** [jupago/TNOC#7]
Add Environmental Ed page.   Page already cerated but needs formatting.  Will have a total of 10 essays eventually.  Should be in the PROJECTS menu bar.  Make a banner for it, and include it among the rotating banners.

**Comment by jupago** [comment]
– Add to Project menu (Green color)
– Add banner to home page
– Edit page to populate posts as they are published
– Project name: Urban Environmental Ed

**Comment by gdmaddox** [comment]
I see the URBAN ENVIRONMENTAL ED page is formatted, so I published it. Two things more:
1. it needs to appear in the PROJECTS menu item
2.  It needs a banner

**Comment by jupago** [comment]
Thanks,
Working on banner now.
Added item to top menu but website (sitelock likely) is pushing the cached CSS file rather than my new one, will give it a few more minutes to see if it serves the latest otherwise I might have to go into Site Lock and clear cached files manually.

**Comment by jupago** [comment]
![environmentaled_banner1000x120](https://cloud.githubusercontent.com/assets/7199966/15127768/231e4a70-1606-11e6-93b4-8513039fc9aa.jpg)

Before I add can you sign off?
Any copy you'd like to add/remove

**Comment by gdmaddox** [comment]
Nice

**Comment by jupago** [comment]
– Banner Working, see screenshot.
– Made Lime green 10% darker so links are a bit more legible

Marking this as closed and making CONTRIBUTORS page priority.
Feel free to reopen if there other issues that come up

![screen shot 2016-05-10 at 10 40 18 pm](https://cloud.githubusercontent.com/assets/7199966/15168717/ebf1a784-1701-11e6-8d6b-4ccc22a962d5.png)
